from pathlib import Path
from html import escape as e
import json

ROOT=Path(__file__).parent
# Commercial source: Documentacion/Casos de exito Rtres.docx and portal catalogue summarized in AUDITORIA-SEO-WEB.md.
SERVICES=[
 dict(slug='diseno-web',name='Diseño web',title='Una web a la altura de tu empresa.',summary='Diseñamos sitios web para pymes y equipos de marketing que necesitan presentar su negocio y recibir consultas.',audience='Empresas que necesitan una primera web o renovar un sitio que ya no representa su negocio.',definition='El diseño web corporativo organiza tus servicios, explica tu propuesta de valor y facilita el contacto. En Rtres planteamos la estructura, el diseño adaptable y los contenidos de cada página para que tus clientes puedan entender qué ofreces y dar el siguiente paso.',items=['Arquitectura de páginas y contenidos','Diseño adaptable a móvil y escritorio','Formulario y canales de contacto','Base de SEO técnico y contenidos'],case='building-connections',faq=[('¿Qué necesitamos para comenzar?','Tu objetivo comercial, servicios, identidad visual y contenido disponible. Revisamos juntos qué falta antes de definir el alcance.'),('¿Se puede renovar mi web actual?','Sí. Revisamos contenidos, URLs y funcionamiento antes de plantear los cambios para cuidar la continuidad del sitio.'),('¿Incluye hosting y mantenimiento?','Se presupuestan según las necesidades del proyecto. Puedes contratar hosting, dominio y soporte por separado.')]),
 dict(slug='software-a-medida',name='Software a medida',title='Software que entiende tu operación.',summary='Desarrollamos sistemas de gestión para empresas que necesitan conectar ventas, procesos y equipos en una misma plataforma.',audience='Empresas con procesos que una herramienta estándar no resuelve y equipos que necesitan centralizar su operación.',definition='El software a medida se desarrolla alrededor de los procesos de tu empresa. Rtres construye plataformas para administrar ventas, talleres, cotizaciones, comisiones y cobranza, con integraciones cuando el proyecto las requiere. El alcance se define después de revisar usuarios, flujos y sistemas existentes.',items=['Análisis de procesos y alcance','Desarrollo de módulos de gestión','Integraciones con sistemas existentes','Evolución y soporte del software'],case='crosland',faq=[('¿Cómo se define el presupuesto?','Revisamos procesos, usuarios, integraciones y prioridades. La propuesta concreta módulos, entregables y condiciones.'),('¿Pueden trabajar con un sistema existente?','Primero evaluamos su arquitectura y estado. Esa revisión permite decidir entre integrar, evolucionar o sustituir módulos.'),('¿Qué pasa después del lanzamiento?','Podemos acordar soporte y evolución continua. La cobertura y los tiempos de atención se definen en el contrato.')]),
 dict(slug='integracion-sap',name='Integración SAP',title='Conecta SAP con tu operación.',summary='Integramos sistemas web con SAP para consultar inventarios y conectar procesos de talleres, repuestos y gestión.',audience='Empresas que utilizan SAP y necesitan conectar sus aplicaciones de gestión con su ERP.',definition='Una integración SAP conecta el ERP con otras aplicaciones de negocio. En los proyectos documentados de Grupo Crosland, Rtres desarrolló consultas de stock, reservas y sincronización de repuestos para sistemas de talleres. Cada nueva integración requiere validar versión, interfaces disponibles y reglas operativas.',items=['Evaluación de interfaces y accesos','Consulta y sincronización de datos','Validación de reglas de negocio','Pruebas y seguimiento de integración'],case='crosland',faq=[('¿Con qué versiones de SAP trabajan?','La compatibilidad se valida con tu equipo técnico antes de presupuestar. No asumimos que todas las versiones y módulos usan la misma interfaz.'),('¿Qué experiencia tienen?','Los casos documentados de Kawasaki y Bajaj, para Grupo Crosland, incluyen integración de inventarios, reservas y repuestos con SAP.'),('¿Necesitamos participación de nuestro equipo de TI?','Sí. Necesitamos coordinar interfaces, credenciales, entornos y reglas de acceso con los responsables de SAP.')]),
 dict(slug='tienda-online',name='Tiendas online',title='Tu catálogo, listo para vender.',summary='Creamos tiendas online para negocios que quieren gestionar productos, pedidos y pagos desde una plataforma propia.',audience='Negocios con un catálogo definido que quieren abrir o mejorar su canal de venta online.',definition='Una tienda online permite presentar productos y gestionar pedidos por internet. Rtres desarrolla el catálogo, la experiencia de compra y la integración de pagos según los requisitos del negocio. Antes de construirla acordamos cómo administrar productos, entregas, moneda y condiciones de venta.',items=['Catálogo y fichas de producto','Carrito y experiencia de compra','Integración de pasarela de pago','Panel para gestionar la tienda'],case=None,faq=[('¿Qué pasarelas pueden integrarse?','Se seleccionan según el país, la moneda y la plataforma. Validamos requisitos y costos del proveedor antes de implementarlas.'),('¿Quién carga los productos?','Acordamos la carga inicial y la capacitación para gestionar el catálogo dentro del alcance del proyecto.'),('¿Incluye logística de envíos?','Definimos las reglas de entrega y las integraciones necesarias contigo. Los servicios de terceros tienen sus propias condiciones.')]),
 dict(slug='api-validacion-dni-ruc',name='APIs de validación',title='Valida datos desde tu sistema.',summary='Integra validaciones de DNI, RUC y cuentas bancarias en los procesos de tu empresa en Perú.',audience='Equipos de producto y desarrollo que necesitan incorporar validaciones a sus flujos de registro o gestión.',definition='Las APIs de validación permiten consultar datos desde una aplicación existente. El catálogo de Rtres contempla validación de DNI, RUC y cuentas bancarias. Disponibilidad, campos de respuesta, límites y condiciones de uso se revisan por servicio antes de contratar la integración.',items=['Definición de consultas necesarias','Acceso e integración con tu aplicación','Revisión de respuestas y errores','Plan de uso según volumen'],case=None,faq=[('¿Qué datos devuelve cada API?','Solicita la ficha técnica vigente. Los campos y la disponibilidad dependen del servicio contratado y su fuente de información.'),('¿Es un servicio oficial de una entidad pública?','Esta propuesta no presenta a Rtres como una entidad pública ni presume acceso oficial. Deben confirmarse proveedor y condiciones de cada consulta.'),('¿Cómo se calcula el plan?','Necesitamos el tipo de consulta y el volumen previsto para definir el plan, límites y condiciones.')]),
 dict(slug='facturacion-electronica-sunat',name='Integración SUNAT',title='Conecta gestión y facturación.',summary='Desarrollamos interfaces de facturación electrónica para conectar los procesos de tu empresa con SUNAT en Perú.',audience='Empresas peruanas que necesitan integrar la emisión y validación de comprobantes con su sistema de gestión.',definition='La integración de facturación electrónica conecta la gestión comercial con el flujo de emisión y validación de comprobantes. Rtres cuenta con un caso documentado para Building Connections. El proyecto comienza revisando tu sistema actual, el proveedor de emisión y los requisitos de la interfaz.',items=['Revisión del flujo de comprobantes','Integración con el sistema comercial','Manejo de respuestas y validaciones','Pruebas de la interfaz'],case='building-connections',faq=[('¿Sustituye a mi proveedor de facturación?','Depende del alcance. Podemos estudiar una integración con tu proveedor actual antes de plantear cambios.'),('¿Qué comprobantes se pueden integrar?','Los tipos de documento se confirman durante el análisis técnico y se detallan en la propuesta.'),('¿Tienen un proyecto de referencia?','Building Connections incluye un sistema de cotizaciones y una interfaz para emisión y validación de facturas electrónicas.')]),
 dict(slug='hosting',name='Hosting empresarial',title='Un lugar para tu web.',summary='Planes de hosting Cloud y WordPress para alojar los sitios y aplicaciones de tu empresa.',audience='Empresas que necesitan alojamiento para su web, tienda o aplicación y un interlocutor para su gestión.',definition='El hosting aloja los archivos y datos necesarios para que una web o aplicación esté disponible. El catálogo de Rtres incluye planes Cloud, WordPress y zona EUR. La elección depende del tráfico, recursos, tecnología, ubicación del público y necesidades de soporte.',items=['Selección del plan y recursos','Configuración del alojamiento','Evaluación de migración','Opciones de respaldo y soporte'],case=None,faq=[('¿Qué plan necesita mi sitio?','Revisamos tecnología, tráfico, almacenamiento y uso de la base de datos antes de recomendar el plan.'),('¿Hay alojamiento para público europeo?','El catálogo contempla hosting zona EUR. Deben confirmarse ubicación, recursos y condiciones vigentes.'),('¿Incluye backups y disponibilidad garantizada?','Las condiciones de respaldo, restauración y disponibilidad deben constar en el plan contratado. No se presume un SLA general.')]),
 dict(slug='mantenimiento-web',name='Mantenimiento y soporte',title='Tu web necesita continuidad.',summary='Acompañamos sitios y sistemas con soporte, actualizaciones y seguimiento de solicitudes desde el portal de clientes.',audience='Empresas que ya tienen una web o un sistema y necesitan atención técnica recurrente.',definition='El mantenimiento ayuda a gestionar incidencias y cambios después del lanzamiento. Rtres ofrece soporte mensual y un portal para registrar solicitudes y seguir su atención. La cobertura, horas, respaldos y tiempos de respuesta se acuerdan de forma específica para cada servicio.',items=['Registro y seguimiento de solicitudes','Actualizaciones según cobertura','Revisión de incidencias técnicas','Evolución mediante cambios acordados'],case='euroamerican',faq=[('¿Qué incluye el soporte?','Depende del plan y contrato: especificamos cobertura, horas y exclusiones antes de comenzar.'),('¿Cómo reporto una incidencia?','Puedes registrar un ticket en el portal de clientes y consultar su seguimiento.'),('¿Hay atención las 24 horas?','No se presume atención 24/7. Horarios y tiempos de respuesta se confirman en el contrato.')]),
 dict(slug='dominios-y-ssl',name='Dominios y SSL',title='La identidad de tu web.',summary='Gestionamos dominios y certificados SSL para empresas que quieren ordenar su presencia digital.',audience='Empresas que necesitan registrar o renovar dominios y administrar los certificados de sus sitios.',definition='El dominio identifica tu sitio y el certificado SSL permite cifrar su conexión. Rtres contempla dominios .pe, .com y .it, además de certificados estándar y wildcard. Disponibilidad, titularidad, renovación y requisitos se confirman antes de contratar.',items=['Consulta de disponibilidad','Gestión del registro y renovación','Configuración de certificados','Seguimiento de vencimientos'],case=None,faq=[('¿Quién será el titular del dominio?','La titularidad y los accesos deben quedar acordados en la contratación.'),('¿Necesito un certificado wildcard?','Depende de si debes cubrir subdominios. Evaluamos tus nombres de dominio y requisitos de infraestructura.'),('¿Cuánto cuesta renovar?','El precio depende de extensión, certificado y proveedor. La propuesta debe indicar costo y periodicidad.')]),
 dict(slug='staff-augmentation-net-sap',name='Equipo .NET / SAP',title='Amplía tu equipo técnico.',summary='Proponemos perfiles .NET y experiencia en integración SAP para ampliar las capacidades de tu equipo de desarrollo.',audience='Responsables de TI y equipos de desarrollo que necesitan capacidad adicional para proyectos empresariales.',definition='Staff augmentation incorpora capacidad de desarrollo a un equipo existente. La propuesta comercial de Rtres contempla perfiles .NET y experiencia en integración SAP. Disponibilidad, responsabilidades, dedicación y condiciones se acuerdan según la necesidad concreta del cliente.',items=['Definición del perfil requerido','Revisión de disponibilidad','Coordinación con tu equipo','Acuerdo de dedicación y entregables'],case='crosland',faq=[('¿Hay perfiles disponibles inmediatamente?','La disponibilidad se confirma antes de presentar una propuesta. No anunciamos incorporaciones inmediatas sin validación.'),('¿Cómo se integra el trabajo con nuestro equipo?','Definimos responsables, herramientas, dedicación y seguimiento con tu equipo de TI.'),('¿Qué modalidad de contratación ofrecen?','El alcance y las condiciones se acuerdan por propuesta, según duración y necesidades del proyecto.')])
]
CASES=[
 dict(slug='crosland',name='Grupo Crosland',sector='Automotriz y servicio técnico',title='Talleres y repuestos conectados con SAP.',challenge='Digitalizar la gestión de talleres y conectar la venta de repuestos con el inventario corporativo.',solution='Sistemas DMS para Kawasaki y Bajaj: órdenes de trabajo, presupuestos, consultas de stock y reservas en SAP. Para Bajaj, módulos de reparaciones, garantías y reclamos a fábrica.',outcome='La solución reúne procesos de taller y acceso al inventario corporativo. El documento describe mejoras operativas; su magnitud está pendiente de medición.',services=['software-a-medida','integracion-sap']),
 dict(slug='euroamerican',name='Euroamerican Assistance',sector='Asistencia internacional',title='Una operación centralizada desde 2008.',challenge='Sostener la gestión comercial y financiera de una operación internacional de asistencia.',solution='Ecosistema central con gestión de productos y ventas, cálculo de comisiones e incentivos, reportes ejecutivos y módulo de cobranza.',outcome='El documento registra una relación tecnológica desde 2008 y continuidad en la evolución del sistema. No aporta cifras de ahorro, disponibilidad ni volumen de operaciones.',services=['software-a-medida','mantenimiento-web']),
 dict(slug='alliance',name='Alliance',sector='Asistencia multinacional',title='Ventas para una operación internacional.',challenge='Centralizar la administración de ventas de una empresa con operación distribuida en varios continentes.',solution='Sistema central de ventas mantenido desde 2008, con administración de productos para distintos mercados y reportes de ingresos.',outcome='Una plataforma común para gestionar productos y ventas. La fuente describe apoyo a la expansión internacional sin cuantificar su impacto.',services=['software-a-medida','mantenimiento-web']),
 dict(slug='building-connections',name='Building Connections',sector='Marketing y publicidad',title='De la presencia web a la facturación.',challenge='Unificar la presencia digital de la agencia y conectar sus procesos de cotización y facturación.',solution='Web corporativa, plataforma de control de cotizaciones e interfaz con SUNAT para la emisión y validación de facturas electrónicas.',outcome='El proyecto conecta presencia digital y gestión comercial. Los tiempos ahorrados y el volumen de comprobantes están pendientes de documentación.',services=['diseno-web','facturacion-electronica-sunat'])
]
EXAMPLE_METRICS={
 'crosland':[('24','talleres conectados'),('35 %','menos tiempo de gestión'),('1.800','órdenes al mes')],
 'euroamerican':[('60','usuarios del sistema'),('8.000','operaciones al mes'),('20 %','menos tiempo administrativo')],
 'alliance':[('5','mercados conectados'),('40','usuarios del sistema'),('4.000','ventas gestionadas al mes')],
 'building-connections':[('45 %','menos tiempo de facturación'),('600','comprobantes al mes'),('12','usuarios del sistema')]
}
BY_SLUG={s['slug']:s for s in SERVICES}
GBP='https://www.google.com/search?sca_esv=3cc28e5c82341c61&rlz=1C5CHFA_enIT1033__1034&sxsrf=APpeQnsKj4F-wrrCnZAnYc1qXAceGr24mg:1790884858579&q=Rtres+Web+Solutions+-+Dise%C3%B1o+de+Sitios+Web&si=APenkKm7iecQ4G6P-TsbSMFKIQtv3EFIqRAFw-i8uEbk55Z-_2oCnFhf5u6N9VL-64kUmOMXFkTY2WwHLDjpDbblBaXXg1sAPeJW9zCA5UvM983e3rFUfg8%3D&uds=AJ5uw1_p2fu4EkZbzvA9FH-tMwgO130jdj1VUZ92CS2OrqRtJOs1Jk5v-bX9xUhhoPkhfFejqRFU2R1iuLcCHllO9VZR8o-NwymYN85Xq3rXp_ac3Wjg0W_6Sb5fDcq01yPkIlvEEb5VplGzkz_MRupyN_feVOSxlQ&sa=X&ved=2ahUKEwiT0tD-zZmXAxU1xgIHHcdKMhAQ3PALegQIGBAE&biw=1440&bih=723&dpr=2#sv=CAESzQEKuQEStgEKd0FKaVQ0dEw3VVVPY1ViMXJ6QTNNWnpVaElLN2ZiakFRX0piQVBDalpRNjBIc1VsZjAwY29DTzdrWDc0UExJSWJYTXhnWE43VkVHRjl0cElJUHVhS0JZTDQ3RkhRV1lSUUlrY3QzRXM2TXVoX3lRcG96dEQ0RlJvEhdFYnktYXRfTkE0YU0tZDhQak1pVDBBZxoiQURzcjlmUkJUdEpkd0lkMTNLWDB2YnlZM1haMW83X25aZxIEODA1MRoBMyoAMAA4AUAAGAAgiuPh2AtKAhAB:~:text=verifican%20las%20opiniones-,Google,-5/5'
def link(slug): return f'{slug}.html'
def cta(service='',text='Pedir presupuesto',cls='btn'):
 return f'<a class="{cls}" href="contacto.html?servicio={e(service)}">{e(text)} <span aria-hidden="true">↗</span></a>'
def shell(title,description,body,active=''):
 return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Rtres Web Solutions</title><meta name="description" content="{e(description)}"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#fafbf8"><link rel="icon" href="assets/logo.png"><link rel="stylesheet" href="assets/propuesta.css"><script src="assets/propuesta.js" defer></script></head><body><a class="skip" href="#contenido">Saltar al contenido</a><div class="preview">Propuesta de diseño · Contenido comercial en revisión <a href="README.md">Ver pendientes</a></div><header><div class="wrap navigation"><a href="index.html" aria-label="Rtres Web Solutions, inicio"><img class="logo" src="assets/logo.png" alt="Rtres Web Solutions" width="130" height="64"></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav">Menú</button><nav id="nav" aria-label="Navegación principal"><a href="servicios.html" {'aria-current="page"' if active=='services' else ''}>Servicios</a><a href="casos-de-exito.html" {'aria-current="page"' if active=='cases' else ''}>Casos de éxito</a><a href="index.html#opiniones">Opiniones</a><a href="contacto.html" {'aria-current="page"' if active=='contact' else ''}>Contacto</a></nav>{cta(cls='btn nav-cta')}</div></header><main id="contenido">{body}</main><footer class="wrap"><div class="footer-grid"><div><img class="logo" src="assets/logo.png" alt="Rtres Web Solutions" width="130" height="64"><p>Web, software e integraciones<br>para empresas que quieren avanzar.</p></div><div><strong>Servicios</strong><a href="diseno-web.html">Diseño web</a><a href="software-a-medida.html">Software a medida</a><a href="integracion-sap.html">Integración SAP</a><a href="servicios.html">Todos los servicios</a></div><div><strong>Conversemos</strong><a href="mailto:info@rtres.net">info@rtres.net</a><a href="contacto.html#canales">WhatsApp y formulario</a><a href="casos-de-exito.html">Casos de éxito</a></div></div><div class="footer-bottom"><span>© 2026 Rtres Web Solutions</span><span>Perú / España / Estados Unidos / Italia</span></div></footer><a class="mobile-cta btn" href="contacto.html">Pedir presupuesto <span aria-hidden="true">↗</span></a></body></html>'''
def band(service='',title='Hablemos de tu próximo proyecto.'):
 return f'<section class="wrap closing"><h2>{title}</h2><p>Cuéntanos qué necesitas. Revisamos el alcance y preparamos una propuesta para tu empresa.</p>{cta(service)}</section>'
def case_card(c):
 return f'<a class="case-card" href="caso-{c["slug"]}.html"><div class="capture"><span>Captura del proyecto</span><small>Pendiente de incorporar</small></div><p class="case-sector">{e(c["sector"])}</p><h3>{e(c["name"])}</h3><p>{e(c["title"])}</p><span class="text-link">Ver caso <span aria-hidden="true">↗</span></span></a>'
def logos():
 return '<section class="wrap trust"><p>Proyectos documentados para empresas como</p><div class="logos">'+''.join(f'<div class="logo-slot" role="img" aria-label="Logo pendiente de {e(c["name"])}"><span>{e(c["name"])}</span><small>Logo pendiente</small></div>' for c in CASES)+'</div></section>'
def service_rows(subset):
 return '<div class="service-rows">'+''.join(f'<a href="{link(s["slug"])}"><h3>{e(s["name"])}</h3><p>{e(s["summary"])}</p><span aria-hidden="true">↗</span></a>' for s in subset)+'</div>'
def metrics(c):
 return '<div class="evidence-note">Datos de ejemplo: estas cifras son inventadas para revisar el diseño. Sustituir antes de publicar.</div><div class="metrics">'+''.join(f'<div class="metric"><strong>{value}</strong><span>{label}</span><small>Dato de ejemplo</small></div>' for value,label in EXAMPLE_METRICS[c['slug']])+'</div>'
def write(name,title,description,body,active=''): (ROOT/name).write_text(shell(title,description,body,active))

home='''<section class="wrap hero"><div class="hero-copy"><p class="eyebrow">Web y software para empresas</p><h1>Tu negocio.<br><span>Su siguiente nivel.</span></h1><p class="lead">Diseño web, software a medida e integraciones para pymes y equipos de TI con planes de crecimiento.</p><div class="actions">'''+cta()+'''<a class="text-link" href="casos-de-exito.html">Explorar proyectos ↗</a></div></div><figure class="hero-art"><img src="assets/concepto-conexiones.png" width="1536" height="1024" alt="Ilustración conceptual de módulos conectados en metal y vidrio verde"><figcaption>Imagen conceptual de marca, generada con IA.</figcaption></figure></section>'''+logos()+'''<section class="wrap section"><h2>La solución empieza<br>por lo que necesitas.</h2><p class="intro">Una presencia web clara. Una operación conectada. Un equipo que acompaña tu crecimiento.</p>'''+service_rows(SERVICES[:3])+'''<a class="text-link all-link" href="servicios.html">Explorar todos los servicios ↗</a></section><section class="wrap section"><div class="section-heading"><h2>El trabajo habla.</h2><p class="intro">Proyectos de gestión, integración y web basados en nuestra documentación comercial.</p></div><div class="case-grid">'''+case_card(CASES[0])+case_card(CASES[3])+'''</div><a class="text-link all-link" href="casos-de-exito.html">Ver todos los casos ↗</a></section><section class="wrap section audience"><h2>Para empresas<br>con algo que resolver.</h2><div class="audience-grid"><article><h3>Pymes y marketing</h3><p>Presentar tus servicios, renovar tu web o abrir una tienda online.</p><a href="diseno-web.html">Explorar diseño web ↗</a></article><article><h3>Operaciones y dirección</h3><p>Centralizar gestión, conectar aplicaciones y ordenar procesos.</p><a href="software-a-medida.html">Explorar software ↗</a></article><article><h3>Equipos de TI</h3><p>Integrar SAP o ampliar capacidad de desarrollo .NET.</p><a href="integracion-sap.html">Explorar integraciones ↗</a></article></div></section><section class="wrap section reviews" id="opiniones"><div><p class="eyebrow">Opiniones de clientes</p><h2>La confianza<br>tiene una fuente.</h2><p class="intro">Consulta las opiniones de Rtres Web Solutions en Google.</p><a class="text-link" href="'''+GBP+'''" target="_blank" rel="noopener">Ver ficha en Google ↗</a></div><div class="review-placeholder"><span class="google-label">Google Business Profile</span><div class="rating" aria-label="5 de 5 estrellas"><strong>5.0</strong><span aria-hidden="true">★★★★★</span></div><h3>6 reseñas. Todas de 5 estrellas.</h3><p>Valoración y cantidad facilitadas por Rtres. Los textos, autores y fechas de las seis reseñas se incorporarán desde la ficha.</p><small>Datos facilitados por la empresa; pendientes de comprobación directa en Google.</small></div></section>'''+band()
write('index.html','Diseño web y software a medida para empresas', 'Rtres desarrolla webs, software a medida e integraciones SAP para empresas. Solicita presupuesto y conoce proyectos documentados.',home)
write('servicios.html','Servicios web, software e integraciones','Explora los servicios de Rtres: diseño web, tiendas online, software, SAP, SUNAT, APIs, hosting y soporte.', '<section class="wrap page-intro"><p class="eyebrow">Servicios de Rtres</p><h1>Un servicio para<br>cada necesidad.</h1><p class="lead">Cada especialidad tiene su propia página, alcance y forma de empezar.</p></section><section class="wrap directory">'+service_rows(SERVICES[:5])+'<h2>Infraestructura y continuidad</h2>'+service_rows(SERVICES[5:])+ '</section>'+band(), 'services')
for s in SERVICES:
 related=next((c for c in CASES if c['slug']==s['case']),None)
 body=f'<div class="wrap breadcrumbs"><a href="servicios.html">Servicios</a><span aria-hidden="true">/</span><span>{e(s["name"])}</span></div><section class="wrap service-hero"><div><p class="eyebrow">{e(s["name"])}</p><h1>{e(s["title"])}</h1><p class="lead">{e(s["summary"])}</p>{cta(s["slug"])}</div><aside class="scope"><span>Para tu empresa</span><h2>Qué podemos hacer</h2><ul>'+''.join(f'<li>{e(x)}</li>' for x in s['items'])+f'</ul><p>Alcance y precio según propuesta.</p></aside></section><section class="wrap section explanation"><h2>{e(s["name"])}:<br>qué incluye el servicio</h2><div><p>{e(s["definition"])}</p><h3>¿Para quién es?</h3><p>{e(s["audience"])}</p></div></section><section class="wrap section process"><h2>Un proceso con claridad.</h2><div class="process-grid"><article><h3>Entender tu necesidad</h3><p>Revisamos objetivos, situación actual y requisitos.</p></article><article><h3>Acordar el alcance</h3><p>Definimos entregables, presupuesto y condiciones.</p></article><article><h3>Construir y acompañar</h3><p>Desarrollamos, validamos y acordamos la continuidad.</p></article></div></section>'
 if related: body+=f'<section class="wrap section related-case"><div><h2>Experiencia aplicada.</h2><h3>{e(related["name"])}</h3><p>{e(related["solution"])}</p><a class="text-link" href="caso-{related["slug"]}.html">Conocer el caso ↗</a></div><div class="capture"><span>Captura del proyecto</span><small>Pendiente de incorporar</small></div></section>'
 body+='<section class="wrap section faq"><h2>Antes de empezar.</h2><div>'+''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in s['faq'])+'</div></section>'+band(s['slug'])
 write(link(s['slug']),s['name']+' para empresas',s['summary'],body,'services')
write('casos-de-exito.html','Casos de éxito y proyectos','Conoce los proyectos documentados de Rtres para Grupo Crosland, Euroamerican Assistance, Alliance y Building Connections.','<section class="wrap page-intro"><p class="eyebrow">Proyectos de Rtres</p><h1>Retos reales.<br>Soluciones concretas.</h1><p class="lead">Conoce el problema, lo que construimos y los servicios detrás de cada proyecto.</p></section><section class="wrap case-grid case-index">'+''.join(case_card(c) for c in CASES)+'</section>'+band(),'cases')
for c in CASES:
 body=f'<div class="wrap breadcrumbs"><a href="casos-de-exito.html">Casos de éxito</a><span aria-hidden="true">/</span><span>{e(c["name"])}</span></div><section class="wrap case-hero"><p class="eyebrow">{e(c["sector"])}</p><h1>{e(c["title"])}</h1><p class="lead">{e(c["name"])}</p>{cta(c["services"][0],"Quiero un proyecto similar")}</section><div class="wrap case-cover capture"><span>Captura de {e(c["name"])}</span><small>Reservado para material autorizado del proyecto</small></div><section class="wrap section case-story"><article><h2>El reto.</h2><p>{e(c["challenge"])}</p></article><article><h2>La solución.</h2><p>{e(c["solution"])}</p></article><article><h2>Lo que podemos demostrar.</h2><p>{e(c["outcome"])}</p>{metrics(c)}</article></section><section class="wrap section"><h2>Servicios de este proyecto.</h2>'+service_rows([BY_SLUG[x] for x in c['services']])+'</section>'+band(c['services'][0], '¿Tu empresa tiene un reto similar?')
 write('caso-'+c['slug']+'.html',c['name']+' | Caso de proyecto',c['challenge'],body,'cases')
form='''<section class="wrap contact-layout"><div><p class="eyebrow">Contacto</p><h1>Hagamos espacio<br>a tu proyecto.</h1><p class="lead">Cuéntanos qué necesita tu empresa. Empecemos por una conversación clara.</p><div class="contact-channels" id="canales"><h2>Elige cómo conversar.</h2><a class="channel" href="mailto:info@rtres.net"><span>Por correo</span><strong>info@rtres.net ↗</strong></a><a class="channel" href="https://wa.me/393281915399" data-whatsapp target="_blank" rel="noopener"><span>Por WhatsApp</span><strong>+39 328 191 5399 ↗</strong></a><small>Atendemos proyectos para Perú, España, Estados Unidos e Italia.</small></div></div><form id="contact-form"><h2>Pedir presupuesto</h2><p>Un poco de contexto nos ayuda a orientarte.</p><div class="form-row"><label>Nombre <input name="nombre" autocomplete="name" required maxlength="100"></label><label>Empresa <input name="empresa" autocomplete="organization" maxlength="150"></label></div><label>Correo de contacto <input name="correo" type="email" autocomplete="email" required maxlength="200"></label><div class="form-row"><label>Mercado <select name="mercado"><option>Perú</option><option>España</option><option>Estados Unidos</option><option>Italia</option><option>Otro</option></select></label><label>Servicio <select name="servicio"><option value="">Quiero orientación</option>'''+''.join(f'<option value="{s["slug"]}">{e(s["name"])}</option>' for s in SERVICES)+'''</select></label></div><label>¿Qué necesitas resolver? <textarea name="mensaje" rows="5" required maxlength="3000" placeholder="Cuéntanos sobre tu proyecto, tu web actual o el proceso que quieres mejorar."></textarea></label><div class="form-note">Mockup: este formulario prepara una vista previa del mensaje. No envía ni guarda datos.</div><button class="btn" type="submit">Revisar solicitud <span aria-hidden="true">↗</span></button><div id="form-status" role="status" aria-live="polite" hidden></div></form></section><dialog id="lead-preview"><div class="dialog-header"><h2>Tu solicitud</h2><button type="button" id="close-preview" aria-label="Cerrar vista previa">Cerrar</button></div><p>Revisa el mensaje antes de abrir tu aplicación de correo.</p><pre id="message-preview"></pre><a class="btn" id="email-draft">Abrir borrador de correo ↗</a><p class="form-note">La solicitud solo se enviará si la envías desde tu aplicación de correo. El formulario de producción requerirá conexión al API y aviso de privacidad.</p></dialog>'''
write('contacto.html','Pedir presupuesto','Contacta con Rtres por correo, WhatsApp o prepara una solicitud de presupuesto para tu web o software.',form,'contact')
print('Generated',len(list(ROOT.glob('*.html'))),'static mockup pages')
