import { MoneyPipe } from '../../core/money.pipe';
import { Component, EventEmitter, Input, Output } from '@angular/core'; import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms';
/** Descuento de monto fijo sobre el precio del catálogo: se ingresa como descuento o como precio final (emite siempre el descuento). */
@Component({selector:'app-discount-field',standalone:true,imports:[MoneyPipe,CommonModule,FormsModule],template:`<fieldset class="space-y-2"><div class="flex items-center justify-between gap-3"><legend class="field-label">Descuento</legend><div class="flex gap-1 text-sm" role="radiogroup" aria-label="Forma de ingresar el descuento"><button type="button" class="btn btn-sm" [class.btn-primary]="mode==='discount'" [class.btn-ghost]="mode!=='discount'" (click)="setMode('discount')" [attr.aria-pressed]="mode==='discount'">Descuento</button><button type="button" class="btn btn-sm" [class.btn-primary]="mode==='final'" [class.btn-ghost]="mode!=='final'" (click)="setMode('final')" [attr.aria-pressed]="mode==='final'">Precio final</button></div></div><input class="field" type="number" step="0.01" min="0" [max]="listPrice" [ngModel]="value" (ngModelChange)="change($event)" [ngModelOptions]="{standalone:true}" [attr.aria-label]="mode==='discount'?'Monto de descuento':'Precio final'" [placeholder]="mode==='discount'?'0.00':listPrice.toFixed(2)"><p class="text-xs text-muted">Catálogo {{listPrice|money:currency}}<ng-container *ngIf="discount"> · paga {{listPrice-discount|money:currency}} (−{{discount|money:currency}})</ng-container>. Precios sin IGV. Vale solo el periodo actual: la renovación se cobra a precio de catálogo.</p><p *ngIf="invalid" class="text-xs text-red-600">{{mode==='discount'?'El descuento':'El precio final'}} debe estar entre 0 y {{listPrice|money:currency}}.</p></fieldset>`})
export class DiscountFieldComponent {
  @Input({required:true}) listPrice=0; @Input() currency='USD';
  @Input() set discount(v:number|null){this._discount=v||null;if(this.value===null)this.value=this.mode==='discount'?this._discount:(this._discount?this.round(this.listPrice-this._discount):null);}
  get discount(){return this._discount;}
  @Output() discountChange=new EventEmitter<number|null>();
  mode:'discount'|'final'='discount'; value:number|null=null; invalid=false; private _discount:number|null=null;
  setMode(mode:'discount'|'final'){if(mode===this.mode)return;this.mode=mode;this.value=this._discount?(mode==='discount'?this._discount:this.round(this.listPrice-this._discount)):null;}
  change(v:number|null){this.value=v;const n=v===null||(v as unknown)===''?null:Number(v);this.invalid=n!==null&&(n<0||n>this.listPrice);if(this.invalid)return;const d=n===null?null:this.round(this.mode==='discount'?n:this.listPrice-n);this._discount=d||null;this.discountChange.emit(this._discount);}
  private round(n:number){return Math.round(n*100)/100;}
}
