using Microsoft.EntityFrameworkCore;
using Rtres.Domain;

namespace Rtres.Infrastructure.Persistence;

public sealed class RtresDbContext(DbContextOptions<RtresDbContext> options) : DbContext(options)
{
    public DbSet<Client> Clients => Set<Client>(); public DbSet<UserAccount> UserAccounts => Set<UserAccount>();
    public DbSet<Project> Projects => Set<Project>(); public DbSet<ProjectRepository> ProjectRepositories => Set<ProjectRepository>(); public DbSet<PortalNotification> PortalNotifications => Set<PortalNotification>(); public DbSet<Product> Products => Set<Product>(); public DbSet<ClientProduct> ClientProducts => Set<ClientProduct>();
    public DbSet<Ticket> Tickets => Set<Ticket>(); public DbSet<TicketAttachment> TicketAttachments => Set<TicketAttachment>(); public DbSet<TicketComment> TicketComments => Set<TicketComment>(); public DbSet<PaymentTransaction> PaymentTransactions => Set<PaymentTransaction>(); public DbSet<NotificationLog> NotificationLogs => Set<NotificationLog>();
    public DbSet<ExchangeRate> ExchangeRates => Set<ExchangeRate>(); public DbSet<TaxDocument> TaxDocuments => Set<TaxDocument>(); public DbSet<Purchase> Purchases => Set<Purchase>(); public DbSet<LearningVideo> LearningVideos => Set<LearningVideo>(); public DbSet<ExpenseCategory> ExpenseCategories => Set<ExpenseCategory>(); public DbSet<ProductCategory> ProductCategories => Set<ProductCategory>(); public DbSet<Expense> Expenses => Set<Expense>(); public DbSet<TaxSettings> TaxSettings => Set<TaxSettings>(); public DbSet<TaxDueDate> TaxDueDates => Set<TaxDueDate>(); public DbSet<BankAccount> BankAccounts => Set<BankAccount>(); public DbSet<PaymentSettings> PaymentSettings => Set<PaymentSettings>(); public DbSet<TransferReport> TransferReports => Set<TransferReport>();
    protected override void OnModelCreating(ModelBuilder b)
    {
        b.Entity<Client>().HasIndex(x => x.Email).IsUnique(); b.Entity<UserAccount>().HasIndex(x => x.Email).IsUnique(); b.Entity<Project>().HasIndex(x => x.Slug).IsUnique(); b.Entity<ClientProduct>().HasIndex(x => x.PayPalSubscriptionId).IsUnique(); b.Entity<ClientProduct>().HasIndex(x => x.PayPalOrderId).IsUnique(); b.Entity<Ticket>().HasIndex(x => x.Code).IsUnique(); b.Entity<Ticket>().HasIndex(x => x.GithubIssueNumber); b.Entity<TicketComment>().HasIndex(x => x.GithubCommentId).IsUnique(); b.Entity<NotificationLog>().HasIndex(x => x.DedupeKey); b.Entity<NotificationLog>().Property(x => x.DedupeKey).HasMaxLength(200);
        b.Entity<Product>().Property(x => x.BasePrice).HasPrecision(12, 2); b.Entity<Product>().Property(x => x.PayPalPlanPrice).HasPrecision(12, 2); b.Entity<ClientProduct>().Property(x => x.Price).HasPrecision(12, 2); b.Entity<ClientProduct>().Property(x => x.Discount).HasPrecision(12, 2); b.Entity<ClientProduct>().Ignore(x => x.AppliedIgvRate); b.Entity<PaymentTransaction>().Property(x => x.Amount).HasPrecision(12, 2); b.Entity<PaymentTransaction>().Property(x => x.AmountPen).HasPrecision(12, 2); b.Entity<PaymentTransaction>().HasIndex(x => x.InternalCode).IsUnique(); b.Entity<PaymentTransaction>().HasIndex(x => new { x.ClientId, x.CreatedAt }); b.Entity<TaxDocument>().Property(x => x.RetentionAmount).HasPrecision(12, 2); b.Entity<PaymentTransaction>().Property(x => x.Method).HasMaxLength(20); b.Entity<PaymentTransaction>().Property(x => x.PayPalOrderIdOrSubscriptionId).HasMaxLength(100); b.Entity<PaymentTransaction>().HasIndex(x => x.PayPalOrderIdOrSubscriptionId).IsUnique();
        // Un repo de GitHub pertenece a un solo proyecto: el webhook ubica el ticket por dueño/nombre del repo.
        b.Entity<ProjectRepository>().HasIndex(x => new { x.Owner, x.Name }).IsUnique(); b.Entity<ExpenseCategory>().Property(x => x.Name).HasMaxLength(100); b.Entity<ExpenseCategory>().HasIndex(x => x.Name).IsUnique(); b.Entity<ExpenseCategory>().Property(x => x.Code).HasMaxLength(50); b.Entity<ExpenseCategory>().HasData(ExpenseCategoryIds.Seed); b.Entity<Expense>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict); b.Entity<ProductCategory>().Property(x => x.Name).HasMaxLength(100); b.Entity<ProductCategory>().HasIndex(x => x.Name).IsUnique(); b.Entity<LearningVideo>().Property(x => x.Title).HasMaxLength(200); b.Entity<Purchase>().Ignore(x => x.TaxCreditPen); foreach (var money in new[] { nameof(Purchase.TaxBase), nameof(Purchase.Igv), nameof(Purchase.NonTaxable), nameof(Purchase.Total), nameof(Purchase.BasePen), nameof(Purchase.IgvPen), nameof(Purchase.TotalPen) }) b.Entity<Purchase>().Property(money).HasPrecision(12, 2); b.Entity<Purchase>().Property(x => x.ExchangeRate).HasPrecision(12, 6); b.Entity<Purchase>().HasIndex(x => new { x.SupplierTaxId, x.DocumentType, x.Series, x.Number }).IsUnique(); b.Entity<Purchase>().HasIndex(x => x.Period); b.Entity<Purchase>().Property(x => x.Series).HasMaxLength(20); b.Entity<Purchase>().Property(x => x.Number).HasMaxLength(20); b.Entity<Purchase>().Property(x => x.SupplierTaxId).HasMaxLength(20); b.Entity<Purchase>().Property(x => x.SupplierName).HasMaxLength(200); b.Entity<Purchase>().Property(x => x.Currency).HasMaxLength(3); b.Entity<Purchase>().Property(x => x.Notes).HasMaxLength(500); b.Entity<LearningVideo>().Property(x => x.YoutubeId).HasMaxLength(11); b.Entity<LearningVideo>().Property(x => x.Category).HasMaxLength(100); b.Entity<LearningVideo>().Property(x => x.Language).HasMaxLength(2); b.Entity<LearningVideo>().Property(x => x.Description).HasMaxLength(500); b.Entity<TicketAttachment>().Ignore(x => x.IsImage); b.Entity<TicketAttachment>().Property(x => x.ContentType).HasMaxLength(100); b.Entity<TicketAttachment>().Property(x => x.FileName).HasMaxLength(255); b.Entity<ProjectRepository>().Property(x => x.Owner).HasMaxLength(100); b.Entity<ProjectRepository>().Property(x => x.Name).HasMaxLength(100); b.Entity<ProjectRepository>().Property(x => x.Label).HasMaxLength(100);
        b.Entity<PortalNotification>().HasIndex(x => new { x.ClientId, x.CreatedAt }); b.Entity<PortalNotification>().HasIndex(x => x.DedupeKey); b.Entity<PortalNotification>().Property(x => x.Type).HasMaxLength(40); b.Entity<PortalNotification>().Property(x => x.DedupeKey).HasMaxLength(200);
        b.Entity<Product>().Property(x => x.Category).HasMaxLength(100); b.Entity<Product>().Property(x => x.Tags).HasMaxLength(500);
        b.Entity<ExchangeRate>().HasIndex(x => new { x.Date, x.CurrencyCode }).IsUnique(); b.Entity<ExchangeRate>().Property(x => x.RateToPen).HasPrecision(12, 6);
        b.Entity<TaxDocument>().HasIndex(x => new { x.Type, x.Series, x.Number }).IsUnique(); b.Entity<TaxDocument>().HasIndex(x => x.PaymentTransactionId).IsUnique().HasFilter("[PaymentTransactionId] IS NOT NULL"); b.Entity<TaxSettings>().Property(x => x.FacturaSeries).HasMaxLength(4); b.Entity<TaxSettings>().Property(x => x.ReciboSeries).HasMaxLength(4); b.Entity<TaxDocument>().Property(x => x.BaseAmount).HasPrecision(12, 2); b.Entity<TaxDocument>().Property(x => x.IgvAmount).HasPrecision(12, 2); b.Entity<TaxDocument>().Property(x => x.TotalAmount).HasPrecision(12, 2);
        b.Entity<Expense>().Property(x => x.Amount).HasPrecision(12, 2); b.Entity<Expense>().Property(x => x.AmountPen).HasPrecision(12, 2);
        b.Entity<TaxSettings>().Property(x => x.Ruc).HasMaxLength(11); b.Entity<TaxDueDate>().HasIndex(x => x.Period).IsUnique(); b.Entity<TaxDueDate>().HasData(TaxDueDateSeed.Rows2026);
        b.Entity<ClientProduct>().Ignore(x => x.TransferReport);
        b.Entity<BankAccount>().Property(x => x.BankName).HasMaxLength(100); b.Entity<BankAccount>().Property(x => x.Holder).HasMaxLength(200); b.Entity<BankAccount>().Property(x => x.Currency).HasMaxLength(3); b.Entity<BankAccount>().Property(x => x.AccountNumber).HasMaxLength(40); b.Entity<BankAccount>().Property(x => x.Cci).HasMaxLength(40); b.Entity<BankAccount>().Property(x => x.Type).HasConversion<string>().HasMaxLength(20);
        b.Entity<TransferReport>().Property(x => x.Amount).HasPrecision(12, 2); b.Entity<TransferReport>().Property(x => x.Currency).HasMaxLength(3); b.Entity<TransferReport>().Property(x => x.OperationNumber).HasMaxLength(60); b.Entity<TransferReport>().Property(x => x.ReceiptFileName).HasMaxLength(255); b.Entity<TransferReport>().Property(x => x.ReceiptContentType).HasMaxLength(100); b.Entity<TransferReport>().Property(x => x.RejectionReason).HasMaxLength(500); b.Entity<TransferReport>().Property(x => x.Status).HasConversion<string>().HasMaxLength(20); b.Entity<TransferReport>().HasIndex(x => new { x.Status, x.CreatedAt }); b.Entity<TransferReport>().HasIndex(x => x.ClientProductId);
        b.Entity<TaxSettings>().Property(x => x.IgvRate).HasPrecision(5, 4); b.Entity<TaxSettings>().Property(x => x.RentaRate).HasPrecision(5, 4);
    }
}
