namespace Rtres.Domain;

public enum UserRole { Admin, Cliente, SuperAdmin }
public enum ProductType { Hosting, Dominio, Ssl, BackupBd, SoporteMensual, DesarrolloWeb }
public enum BillingCycle { Unico, Mensual, Anual }
public enum ClientProductStatus { Activo, PorVencer, Vencido, Cancelado, Pendiente }
public enum TicketType { Bug, Funcionalidad, Requerimiento } // mismos valores 0/1 que los antiguos Soporte/Cambio
public enum TicketStatus { Abierto, EnProgreso, Resuelto, Publicado, Cerrado }

public sealed class Client { public Guid Id { get; set; } = Guid.NewGuid(); public string CompanyName { get; set; } = string.Empty; public string ContactName { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string? Phone { get; set; } public string PreferredLanguage { get; set; } = "es"; public bool IsActive { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public sealed class UserAccount { public Guid Id { get; set; } = Guid.NewGuid(); public Guid? ClientId { get; set; } public string Email { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public UserRole Role { get; set; } = UserRole.Cliente; public bool IsActive { get; set; } = true; }
public sealed class Project { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ClientId { get; set; } public string Name { get; set; } = string.Empty; public string Slug { get; set; } = string.Empty; public string GithubRepoOwner { get; set; } = string.Empty; public string GithubRepoName { get; set; } = string.Empty; }
public sealed class Product { public Guid Id { get; set; } = Guid.NewGuid(); public ProductType Type { get; set; } public string Name { get; set; } = string.Empty; public BillingCycle BillingCycle { get; set; } public decimal? BasePrice { get; set; } public string Currency { get; set; } = "USD"; public string? Description { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ClientProduct { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ClientId { get; set; } public Guid ProjectId { get; set; } public Guid ProductId { get; set; } public ClientProductStatus Status { get; set; } public BillingCycle BillingCycle { get; set; } public bool IsManualBilling { get; set; } public DateTime? RenewsAt { get; set; } public DateTime? NextChargeAt { get; set; } public DateTime? LastBackupAt { get; set; } public decimal? Price { get; set; } public string? PriceLabelOverride { get; set; } public string? PayPalOrderId { get; set; } public string? PayPalSubscriptionId { get; set; } public string? PayPalPlanId { get; set; } public string? DomainName { get; set; } public Product? Product { get; set; } public Project? Project { get; set; } }
public sealed class Ticket { public Guid Id { get; set; } = Guid.NewGuid(); public string Code { get; set; } = string.Empty; public Guid ClientId { get; set; } public Guid ProjectId { get; set; } public Guid CreatedByUserId { get; set; } public TicketType Type { get; set; } public TicketStatus Status { get; set; } = TicketStatus.Abierto; public string Title { get; set; } = string.Empty; public string Description { get; set; } = string.Empty; public string? CurrentBehavior { get; set; } public string? ExpectedBehavior { get; set; } public string? StepsToReproduce { get; set; } public string? Environment { get; set; } public string? AcceptanceCriteria { get; set; } public string? EstimatedImpact { get; set; } public int? GithubIssueNumber { get; set; } public string? GithubIssueUrl { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; }
public sealed class TicketAttachment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid TicketId { get; set; } public string FileName { get; set; } = string.Empty; public string Url { get; set; } = string.Empty; public long SizeBytes { get; set; } }
public sealed class TicketComment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid TicketId { get; set; } public Guid? AuthorUserId { get; set; } public string Body { get; set; } = string.Empty; public bool FromGithub { get; set; } public long? GithubCommentId { get; set; } public string? GithubAuthorLogin { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public sealed class PaymentTransaction { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ClientProductId { get; set; } public string PayPalOrderIdOrSubscriptionId { get; set; } = string.Empty; public decimal Amount { get; set; } public string Currency { get; set; } = "USD"; public string Status { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public sealed class NotificationLog { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ClientId { get; set; } public string Type { get; set; } = string.Empty; public string Channel { get; set; } = string.Empty; public DateTime SentAt { get; set; } = DateTime.UtcNow; public bool Success { get; set; } }
