import { MoneyPipe } from '../../core/money.pipe';
import { Component, EventEmitter, Input, Output, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { BankTransferInfo, PREPAID_YEARS, PaymentMethod, PortalApiService, ProductDto, ProjectDto } from '../../core/portal-api.service';
import { BankTransferInfoComponent } from '../bank-transfer-info/bank-transfer-info.component';

@Component({selector:'app-subscribe-dialog',standalone:true,imports:[MoneyPipe,CommonModule,FormsModule,BankTransferInfoComponent],template:`<div class="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section class="card w-full max-w-lg p-6" role="dialog" aria-modal="true" [attr.aria-label]="'Agregar '+product.name"><h2 class="font-display text-xl">Agregar {{product.name}}</h2><ng-container *ngIf="!transferInfo();else requested"><p class="text-muted mt-1">Confirma el proyecto, el ciclo y cómo vas a pagar.</p><label class="field-label mt-5">Proyecto<select class="field" [(ngModel)]="projectId"><option value="" disabled>Selecciona un proyecto</option><option *ngFor="let project of projects" [value]="project.id">{{project.name}}</option></select></label><label class="field-label mt-3">Ciclo de facturación<select class="field" [(ngModel)]="billingCycle"><option [value]="product.billingCycle">{{cycleLabel(product.billingCycle)}}</option></select></label><label *ngIf="product.billingCycle==='Anual'" class="field-label mt-3">Años a pagar<select class="field" [(ngModel)]="years"><option *ngFor="let y of yearOptions" [ngValue]="y">{{y===1?'1 año':y+' años por adelantado'}}</option></select><span *ngIf="total() as t" class="text-xs text-muted">Total: {{t|money:product.currency}}{{product.igvRate?' (incluye IGV)':''}}</span></label><fieldset class="mt-4"><legend class="field-label">Forma de pago</legend><div class="grid gap-2 mt-1"><label class="flex items-start gap-2 text-sm cursor-pointer"><input type="radio" name="paymentMethod" value="Transferencia" [(ngModel)]="paymentMethod" class="mt-1"><span>Transferencia bancaria<span class="block text-muted">Te mostramos los datos de la cuenta; el producto se activa cuando Rtres confirme el pago.</span></span></label><label class="flex items-start gap-2 text-sm cursor-pointer"><input type="radio" name="paymentMethod" value="PayPal" [(ngModel)]="paymentMethod" class="mt-1"><span>PayPal<span class="block text-muted">Pago con tarjeta o cuenta PayPal; se activa al instante.</span></span></label></div></fieldset><p *ngIf="error()" class="text-warn text-sm mt-3">{{error()}}</p><div class="flex gap-2 mt-6"><button class="btn btn-primary btn-sm" (click)="continue()" [disabled]="!projectId || loading()">{{loading() ? 'Preparando…' : paymentMethod==='PayPal' ? 'Continuar a PayPal' : 'Solicitar producto'}}</button><button class="btn btn-ghost btn-sm" (click)="closed.emit()">Cancelar</button></div></ng-container><ng-template #requested><p class="text-muted mt-1">Listo: el producto quedó pendiente de pago.</p><app-bank-transfer-info class="block mt-4" [info]="transferInfo()!"/><div class="flex gap-2 mt-6"><button class="btn btn-primary btn-sm" (click)="done()">Entendido</button></div></ng-template></section></div>`})
export class SubscribeDialogComponent {
  private api=inject(PortalApiService); @Input({required:true}) product!:ProductDto; @Input() projects:ProjectDto[]=[]; @Output() closed=new EventEmitter<void>();
  years=1; yearOptions=PREPAID_YEARS;
  /** Total por los años elegidos: precio sin IGV × años, más IGV si aplica (el backend calcula el monto real). */
  total(){const p=this.product.basePrice;return p==null?null:Math.round(p*this.years*(1+(this.product.igvRate??0))*100)/100;}
  projectId=''; billingCycle=''; paymentMethod:PaymentMethod='Transferencia'; loading=signal(false); error=signal(''); transferInfo=signal<BankTransferInfo|null>(null);
  ngOnInit(){this.billingCycle=this.product.billingCycle;}
  cycleLabel(value:string){return value==='Unico'?'Pago único':value;}
  continue(){this.loading.set(true);this.error.set('');this.api.subscribeProduct({productId:this.product.id,projectId:this.projectId,billingCycle:this.billingCycle,paymentMethod:this.paymentMethod,years:this.product.billingCycle==='Anual'?this.years:1}).subscribe({next:r=>{if(r.approvalUrl){location.assign(r.approvalUrl);return;}this.loading.set(false);this.transferInfo.set(r.bankTransfer??{instructions:'',amount:null,currency:this.product.currency});},error:e=>{this.error.set(e.error?.message ?? 'No se pudo agregar el producto.');this.loading.set(false);}});}
  /** El producto ya existe como Pendiente: se recarga para que aparezca en "Mis productos". */
  done(){this.router.navigateByUrl('/dashboard');}
  private router=inject(Router);
}
