import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PortalApiService, ProductDto, ProjectDto } from '../../core/portal-api.service';
import { SubscribeDialogComponent } from '../subscribe-dialog/subscribe-dialog.component';
import { PortalUiService } from '../../core/portal-ui.service';
import { EnumLabelPipe } from '../../core/enum-labels';

@Component({selector:'app-catalog',standalone:true,imports:[CommonModule,SubscribeDialogComponent,EnumLabelPipe],template:`<h1 class="font-display text-2xl font-semibold">Catálogo de productos</h1><p class="text-muted mt-1">Agrega servicios activos a tus proyectos.</p><div class="grid md:grid-cols-2 xl:grid-cols-3 gap-5 mt-7"><article class="card p-6" *ngFor="let product of products()"><p class="text-muted text-sm">{{product.type | enumLabel:'productType'}}</p><h2 class="font-display text-xl mt-2">{{product.name}}</h2><p class="text-muted text-sm mt-2" *ngIf="product.description">{{product.description}}</p><p class="mt-5 font-semibold">{{product.basePrice == null ? 'Consultar' : (product.currency + ' ' + (product.basePrice|number:'1.2-2'))}}<ng-container *ngIf="product.basePrice != null && product.igvRate"> + IGV</ng-container> <span class="text-muted font-normal">/ {{product.billingCycle === 'Unico' ? 'único' : product.billingCycle.toLowerCase()}}</span></p><button class="btn btn-primary btn-sm mt-5" (click)="selected.set(product)">Agregar</button></article></div><app-subscribe-dialog *ngIf="selected() as product" [product]="product" [projects]="projects()" (closed)="selected.set(null)"/>`})
export class CatalogComponent implements OnInit {private api=inject(PortalApiService);private ui=inject(PortalUiService);products=signal<ProductDto[]>([]);projects=signal<ProjectDto[]>([]);selected=signal<ProductDto|null>(null);ngOnInit(){this.ui.breadcrumb.set({current:'Catálogo'});this.api.getCatalogProducts().subscribe(x=>this.products.set(x));this.api.getProjects().subscribe(x=>this.projects.set(x));}}
